apiVersion: v1
kind: ConfigMap
metadata:
  name: high-throughput-profile
data:
  kafka-profile: |
    resources:
      requests:
        cpu: 2000m
        memory: 4Gi
      limits:
        cpu: 4000m
        memory: 8Gi
    jvm:
      heapSize: 3Gi
      gcConfig: "-XX:+UseG1GC -XX:MaxGCPauseMillis=20"

  spark-profile: |
    resources:
      requests:
        cpu: 2000m
        memory: 4Gi
      limits:
        cpu: 4000m
        memory: 8Gi
    spark:
      executorMemory: 3Gi
      executorCores: 2 
