apiVersion: v1
kind: Service
metadata:
  name: prometheus
spec:
  ports:
  - port: 9090
    targetPort: 9090
  selector:
    app: prometheus
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prometheus
  template:
    metadata:
      labels:
        app: prometheus
    spec:
      containers:
      - name: prometheus
        image: prom/prometheus:latest
        ports:
        - containerPort: 9090
        volumeMounts:
        - name: prometheus-config
          mountPath: /etc/prometheus/prometheus.yml
          subPath: prometheus.yml
        - name: prometheus-data
          mountPath: /prometheus
      volumes:
      - name: prometheus-config
        configMap:
          name: prometheus-config
      - name: prometheus-data
        emptyDir: {}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
    scrape_configs:
      - job_name: 'prometheus'
        static_configs:
          - targets: ['localhost:9090']
      - job_name: 'kafka'
        static_configs:
          - targets: ['kafka:29092']
      - job_name: 'elasticsearch'
        static_configs:
          - targets: ['elasticsearch:9200']
      - job_name: 'redis'
        static_configs:
          - targets: ['redis:6379']
      - job_name: 'airflow'
        static_configs:
          - targets: ['airflow-webserver:8080']
      - job_name: 'spark'
        static_configs:
          - targets: ['spark-master:8080']
      - job_name: 'api'
        static_configs:
          - targets: ['api:3000']
