apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  name: istio-monitoring
spec:
  profile: default
  components:
    egressGateways:
    - enabled: true
    ingressGateways:
    - enabled: true
    pilot:
      k8s:
        resources:
          requests:
            cpu: 500m
            memory: 2048Mi
          limits:
            cpu: 1000m
            memory: 4096Mi
