global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
- job_name: 'prometheus'
  static_configs:
  - targets: [ 'localhost:9090' ]

- job_name: 'kafka'
  static_configs:
  - targets: [ 'kafka:29092' ]

- job_name: 'elasticsearch'
  static_configs:
  - targets: [ 'elasticsearch:9200' ]

- job_name: 'redis'
  static_configs:
  - targets: [ 'redis:6379' ]
  metrics_path: /metrics

- job_name: 'redis-exporter'
  static_configs:
  - targets: [ 'redis-exporter:9121' ]

- job_name: 'airflow'
  static_configs:
  - targets: [ 'airflow-webserver:8080' ]

- job_name: 'spark'
  static_configs:
  - targets: [ 'spark-master:8080' ]

- job_name: 'api'
  static_configs:
  - targets: [ 'api:3000' ]
