apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: elasticsearch-vpa
spec:
  targetRef:
    apiVersion: apps/v1
    kind: StatefulSet
    name: elasticsearch
  updatePolicy:
    updateMode: "Auto"
  resourcePolicy:
    containerPolicies:
    - containerName: '*'
      minAllowed:
        memory: "256Mi"
        cpu: "100m"
      maxAllowed:
        memory: "4Gi"
        cpu: "1000m"
---
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: spark-master-vpa
spec:
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: spark-master
  updatePolicy:
    updateMode: "Auto"
