apiVersion: v1
kind: ConfigMap
metadata:
  name: load-test-config
data:
  k6-script.js: |
    import http from 'k6/http';
    import { check, sleep } from 'k6';

    export let options = {
      stages: [
        { duration: '5m', target: 100 },
        { duration: '10m', target: 100 },
        { duration: '5m', target: 0 },
      ],
      thresholds: {
        http_req_duration: ['p(95)<500'],
        http_req_failed: ['rate<0.01'],
      },
    };

    export default function() {
      let response = http.get('http://api-service:3000/health');
      check(response, {
        'is status 200': (r) => r.status === 200,
      });
      sleep(1);
    } 
